language: ruby
rvm:
  - 2.3.5
services:
  - postgresql
env:
  - ENV=test
before_script:
  - psql -c 'create database test_ledger;' -U postgres
  - gem install bundler
  - bundle exec rake db:reset
script:
  - bundle exec rspec spec
